version: '3.3'

services:
  app-blog:
    build:
      context: .
      dockerfile: Dockerfile
    image: app-blog
    container_name: app-blog
    environment:
      DB_HOST: db-blog
      DB_PORT: 3306
      DB_DATABASE: blog
      DB_USERNAME: root
      DB_PASSWORD: blog
      # FILESYSTEM_DRIVER: public
    networks:
      - blog-network
    depends_on:
      - db-blog
    volumes:
      - ./:/var/www

  db-blog:
    image: mysql:5.7.22
    container_name: db-blog
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: blog
      MYSQL_DATABASE: blog
    volumes:
      - db-blog:/var/lib/mysql/
    networks:
      - blog-network

  nginx-blog:
    image: nginx:latest
    container_name: nginx-blog
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app-blog
    networks:
      - blog-network

networks:
  blog-network:
    driver: bridge

volumes:
  db-blog: