apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-blog
spec:
  selector:
    matchLabels:
      app: app-blog
  template:
    metadata:
      labels:
        app: app-blog
    spec:
      containers:
        - name: app-blog
          image: app-blog
          imagePullPolicy: IfNotPresent
          env:
            - name:  PORT
              value: "8080"
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
          ports:
            - containerPort: 8080
              name: http
---
apiVersion: v1
kind: Service
metadata:
  name: app-blog
spec:
  selector:
    app: app-blog
  ports:
  - port:  80
    targetPort: http
